# Generated by Django 5.1 on 2024-08-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiclick',
            old_name='timestamp',
            new_name='data',
        ),
    ]
